keys:
  - &golden 73B3D1C4840927F5613FC6095F9FD44A71A8A4F2
  - &mastadon age16kjg83an3uw4fcdu0m9agkss96hl677492wj7jdad7dfxqu5ducqg0lad8
creation_rules:
  - path: containers/mastodon-bot/secrets.yaml
    key_groups:
    - pgp:
      - *golden
      age:
       - *mastadon
